### ISSUE TITLE
Array has performance issues

### ISSUE THREAD

**Issue by ae86yyk** [konvajs/konva#1020] opened 2020-11-27 03:45 UTC
```
<!-- <script src='https://unpkg.com/konva/konva.js'></script> -->
    <script>
      let arr = []
      arr.length = 50000
      for (let i = 0; i < 100; i++) {
        console.time("t")
        arr.splice(1, 0, 1);
        console.timeEnd('t')
      }
    </script>
```
Run without konva first,
```
t: 0.4248046875 ms
t: 0.02001953125 ms
t: 0.01611328125 ms
t: 0.018798828125 ms
t: 0.016845703125 ms
t: 0.01611328125 ms
t: 0.01513671875 ms
```
then run with konva
```
t: 3.30908203125 ms
t: 3.676025390625 ms
t: 4.98291015625 ms
t: 3.531982421875 ms
t: 2.984130859375 ms
t: 3.436767578125 ms
```
There's a big time difference, It should be fixed.

After running with Konva once, you must close the tab and reopen, or delete Konva and the result remains unchanged.

**Comment by lavrton** [comment] 2020-11-27 14:15
I can't reproduce it. Konva is not changing array internals. So I don't think the issue is in Konva.

**Comment by lavrton** [comment] 2020-11-27 14:15
Can you make online demos?

**Comment by ae86yyk** [comment] 2020-11-28 08:39
without konva   https://codepen.io/ae86yyk/pen/jOMEbyM    -------total about  3ms
with konva  https://codepen.io/ae86yyk/pen/ExgaVZQ   --------total about  300ms
After run the second demo, rerun the first, the result is also about  300ms. 
Close the second demo, rerun the first, the result is about  3ms.

**Comment by ae86yyk** [comment] 2020-11-28 09:01
@lavrton 
I ran the test again.
Using Safari on MAC, the results of the two demos are the same at around 170ms, but the results are different with Chrome.

**Comment by ae86yyk** [comment] 2020-11-28 09:12
I think the problem might be in the dependencies that you use.

**Comment by lavrton** [comment] 2020-12-28 22:29
I am going to close the issue as a very low priority.

Browsers JS engines have their own optimization tricks. And probably some Konva code is breaking Chrome rules or expectations. My guess is that our Array usage in the Collection module can do that.

We are using JS correctly without some magic. So I don't think we should do any immediate action from Konva side. Also Chrome optimizations logic can change over time.

**Closed by lavrton** 2020-12-28 22:29 UTC
