### ISSUE TITLE
You can't change the size of Sprite object

### ISSUE THREAD

**Issue by leksito** [konvajs/konva#143] opened 2016-04-13 15:39 UTC
If you create Sprite object and use functions width() heigth() size() setHeight() setWidth() and others to resize the Sprite object, these methods don't work. But if we get width or height, we get new value
`
    var width = window.innerWidth;
    var height = window.innerHeight;

```
var stage = new Konva.Stage({
  container: 'container',
  width: width,
  height: height
});

var layer = new Konva.Layer();
var animations = {
  idle: [
    2, 2, 70, 119,
    71, 2, 74, 119,
    146, 2, 81, 119,
    226, 2, 76, 119
  ],
};
var blob;
var imageObj = new Image();
imageObj.onload = function() {  
  blob = new Konva.Sprite({
    x: 50,
    y: 50,
    image: imageObj,
    animation: 'idle',
    animations: animations,
    frameRate: 7,
    frameIndex: 0
  });

  // add the shape to the layer
  layer.add(blob);

  // add the layer to the stage
  stage.add(layer);

  // start sprite animation
  blob.start();
};
imageObj.src = 'http://konvajs.github.io/assets/blob-sprite.png';
blob.size({width: 200, height: 200});
//or
blob.setWidth(200);
blob.setHeight(200);
//and others
console.log(blob.getWidth(), blob.getHeight()); // 200, 200, but the image does not change size
```

`
i tested this script on Mozilla and Chrome and this methods don't work anywhere

**Comment by songoffire** [comment] 2016-04-13 16:15
Are you redrawing your stage and/or layer after re-sizing?  like so:
blob.setWidth(200);
blob.setHeight(200);
layer.draw();

**Comment by leksito** [comment] 2016-04-13 16:45
yep, sure. Now i know how to fix it. 
here https://github.com/konvajs/konva/blob/master/src/shapes/Sprite.js in 105 line: 

            if(image) {
                if (offsets) {
                    var offset = offsets[anim],
                    ix2 = index * 2;
                    context.drawImage(image, x, y, width, height, offset[ix2 + 0], offset[ix2 + 1], width, height);
                } else {
                    context.drawImage(image, x, y, width, height, 0, 0, width, height);
                }
            }


109  context.drawImage(image, x, y, width, height, offset[ix2 + 0], offset[ix2 + 1], **width, height**)
111  context.drawImage(image, x, y, width, height, 0, 0, **width, height**);
if we change highligthed parts to the values which we want, then it will work.

**Comment by leksito** [comment] 2016-04-13 17:01
if (image) {
      spriteWitdh = this.getWidth()() || width;
      spriteHeight = this.getHeight()() || height;
      if (offsets) {
        offset = offsets[anim];
        ix2 = index * 2;
        return context.drawImage(image, x, y, width, height, offset[ix2 + 0], offset[ix2 + 1], spriteWidth, spriteHeight);
      } else {
        return context.drawImage(image, x, y, width, height, 0, 0, spriteWidth, spriteHeight);
      }
    }

**Comment by NecroTheif** [comment] 2016-04-13 22:44
You can also use the scale property of the sprite and that will work.

**Comment by leksito** [comment] 2016-04-14 09:49
it doesn't quite fit. Because I need to set the exact value

**Comment by NecroTheif** [comment] 2016-04-14 12:00
To set exact size set scale to wantedWidth/pixelWidth  and wantedHeight/pixelHeight. Your pixel size is set in your animations.

**Comment by lavrton** [comment] 2016-04-15 03:11
Hmm. I am not sure we need any fix in Konva for this. It is unclear what `width` and `height` mean in a context of `Konva.Sprite` as each frame can have their own width and height. So probably scale is the best way to change Sprite size.

**Comment by leksito** [comment] 2016-04-15 08:51
imho if we have frames with own value of size, then we can set width and height in 0(or we can make the new methods eg, setOriginalSize()). Then we'll have sprite with original size which we set in 'animations'. And we can also change the size by the scale.
Sprite has methods (size, setWidth, setHeight, Width, Height) that create useless properties (width, height) which are not used anywhere. But documentation does not have information about this.
I am not sure that my answer about how to fix this problem is true. but I think need to change information in documentation about this or need to fix this in Konva.

**Comment by lavrton** [comment] 2020-09-14 20:56
I am going to close the issue for now as a super low priority. The way to solve the issue is to just use `scaleX` and `scaleY` of Sprite to adjust its visual size.

**Closed by lavrton** 2020-09-14 20:56 UTC
Labels: enhancement
