### ISSUE TITLE
event on stage dragend trigger mousemove,

### ISSUE THREAD

**Issue by june6969** [konvajs/konva#876] opened 2020-03-17 13:00 UTC
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/konva@4.2.0/konva.min.js"></script>
    <meta charset="utf-8" />
    <title>Konva Stage Events Demo</title>
    <style>
      body {
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #f0f0f0;
      }
    </style>
  </head>

  <body>
    <div id="container"></div>
    <script>
      var width = window.innerWidth;
      var height = window.innerHeight;

      var stage = new Konva.Stage({
        container: 'container',
        width: width,
        height: height,
        draggable:true,
        dragBoundFunc: () => {
        return { x: 0, y: 0 };
      }
      });

      var layer = new Konva.Layer();
      // add the layer to the stage
      stage.add(layer);

      var circle = new Konva.Circle({
        x: stage.width() / 2,
        y: stage.height() / 2,
        fill: 'blue',
        radius: 30
      });

      layer.add(circle).draw();

      stage.on('mousemove mouseover dragstart dragmove dragend ',e=>{
        console.error(e.type);
      })
    </script>
  </body>
</html>

**Comment by lavrton** [comment] 2020-03-18 13:02
I can't reproduce. I created this demo: https://jsbin.com/meleceqoya/1/edit?html,js,output

When I mouseup I see only `dragend` event

**Comment by lavrton** [comment] 2020-03-25 14:54
I am closing the issue for now. If you still have the issue, please provide a demo.

**Closed by lavrton** 2020-03-25 14:54 UTC
