### ISSUE TITLE
Transformer with multiple node 

### ISSUE THREAD

**Issue by sineus** [konvajs/konva#767] opened 2019-10-18 14:08 UTC
Hello everyone,

I would like to select two elements and transform them without grouping them. Is it possible to improve the Transformer object with the ability to add multiple nodes? it would be absolutely great.

Thank you in advance, your library is great.

**Comment by lavrton** [comment] 2019-10-18 20:58
Yeah, I was thinking about that feature too. I think we can implement it.

**Comment by sineus** [comment] 2019-10-19 14:21
Cool ! thanks @lavrton

**Comment by sineus** [comment] 2019-10-21 17:50
Hello @lavrton, after several thoughts, I found a small solution to my problem
https://stackblitz.com/edit/konva-selection

I hope this can help people the time you implement an enhancement for the Transformer

**Comment by FlyDreame** [comment] 2019-11-19 06:02
I need that feature too. I wonder when it will be finished. Thanks.

**Comment by lavrton** [comment] 2020-04-02 15:05
I have very large progress in this task. It is not released yet, but available on master branch of the repo.

The API is:

```javascript
const tr = new Konva.Transformer();
tr.nodes([rect, circle]);
```

**Comment by enriqueerrando** [comment] 2020-04-09 06:49
Hi lavrton,

How is this enhancement going?

We greatly appreciate u're about to release it ;) We're really excited!!

**Comment by lavrton** [comment] 2020-04-09 14:52
It is going well. You can try it right now. Just use `konva.js` or `konva.min.js` from the repo.

**Comment by enriqueerrando** [comment] 2020-04-14 06:59
Sorry for the delay!

Is it implemented in Konva already or do I have to look into the master branch?

Thanks!

**Comment by enriqueerrando** [comment] 2020-04-14 07:09
BTW how did u do it? 

Did u added it as a Transformer parameter that we can turn on and off, or did u implemented it some other way?

**Comment by lavrton** [comment] 2020-04-14 14:26
master branch, not published version yet.

**Comment by enriqueerrando** [comment] 2020-04-15 07:04
But... how can I use it?

**Comment by sineus** [comment] 2020-04-15 07:17
> But... how can I use it?

`const​ ​tr​ ​=​ ​new​ ​Konva.Transformer​();
​tr​.​nodes​([rect, circle]);`

**Comment by sineus** [comment] 2020-04-15 07:17
@lavrton thanks!!

**Comment by enriqueerrando** [comment] 2020-04-15 07:25
> > But... how can I use it?
> 
> `const​ ​tr​ ​=​ ​new​ ​Konva.Transformer​(); ​tr​.​nodes​([rect, circle]);`

Oh! That means that the Transformer works with feature as default, right? If that's the case, cool!!!

**Comment by lavrton** [comment] 2020-04-15 14:57
Yes, it will have almost the same API. For now `tr.setNode(node)` and `tr.attachTo(node)`  are replaced with `tr.nodes([node]);`.

**Comment by enriqueerrando** [comment] 2020-04-16 07:56
It works!!!! Today I'm going to clean up my code and add this feature to test it further ;)

We sincerely appreciate u're hard work!

**Comment by enriqueerrando** [comment] 2020-04-16 08:52
> Yes, it will have almost the same API. For now `tr.setNode(node)` and `tr.attachTo(node)` are replaced with `tr.nodes([node]);`.

Once published, will still use tr.nodes([node]) instead of the current ones?

**Comment by lavrton** [comment] 2020-04-16 15:47
Old API will work for awhile, but with a deprecation warning.

**Comment by enriqueerrando** [comment] 2020-04-17 06:00
That's great because setNode and attachTo are pretty much the same ;)

We really think this feature not only will help us a lot, but others too because this is the natural behaviour most people would expect from groupping nodes. 

More than that will make another difference in order to decide which canvas library to use in the first place ;)

**Comment by enriqueerrando** [comment] 2020-04-17 08:14
And what would be the best way to add new nodes to an existing Transformer? Something like this?

`tr.nodes().push(node);`

**Comment by enriqueerrando** [comment] 2020-04-17 09:17
I've found that if I use push like so `tr.nodes().push(node);` the `layer.draw();` won't update changes, so I've had to define an array first with the current tr nodes and push into that array like so:

`tr_arr.push(new_node);
tr.nodes(tr_arr);
layer.draw();`

**Comment by enriqueerrando** [comment] 2020-04-17 11:04
Does drag and drop work for the new feature when tr has multiple nodes? Even though the tr is still attachaed to multiples nodes and updates correctly on every movement, is only dragging the item touched directly by the mouse. Do I need to do something else?

**Comment by enriqueerrando** [comment] 2020-04-17 11:32
Just in case u didn't notices, now that the tr is attached to multiple individual nodes instead of a group of nodes, drag & drop functionality doesn't work as expected, now u can only drag the node u hit with the mouse. Tr updates fine always grouping all attached nodes, but there is only one node moving around.

**Comment by lavrton** [comment] 2020-04-17 15:08
This will not work: `tr.nodes().push(node);`
Need something like: `tr.nodes(tr.nodes().concat([node))`.

> drag & drop functionality doesn't work as expected

I am going to work on it.

**Comment by enriqueerrando** [comment] 2020-04-20 06:46
Thanks, I'll wait ;)

**Comment by lavrton** [comment] 2020-04-21 21:34
Done. Try `konva@5.0.0`.

Have any bugs? Create an issue here.

**Comment by enriqueerrando** [comment] 2020-04-21 22:32
WOW!! Great news!!

Tomorrow morning I'll try it and let u know if there are any issues, but if u've decided to publish it I'm pretty sure it will work as expected ;)

Thank u!

**Comment by lavrton** [comment] 2020-04-22 03:23
I still need to do some extra work when nodes are rotated.

**Comment by enriqueerrando** [comment] 2020-04-24 07:32
Sorry for the delay, I finally had the time to test Konva 5 ;)

I've found a drag&drop issue with konva 5, do u want me to create new issues for the ones I found or leave them here?

Meanwhile...

The issue happens more often when I multiselect 2 nodes of consecutive indexes, then drag&drop goes crazy moving each item in different directions, pretty weird. In other hand, if the selected nodes have other unselected nodes inbetween, drag&drop works fine most of the time, hehehe.

At first thought that could have something to do with dragBoundFunc, since dragBoundFunc is applied to nodes instead of applying it to the tr itself. I've disabled all dragBoundFunc to make sure wasn't messing up the multiselection tr drag&drop and still not working.

BTW, it would be great being able to apply the dragBoundFunc to the tr, that would help a lot ;)

**Comment by enriqueerrando** [comment] 2020-04-24 07:42
Another thing is that sometimes tr suddenly unattaches itself from its nodes. Mostly after an scalation...

**Comment by lavrton** [comment] 2020-04-24 14:13
> then drag&drop goes crazy moving each item in different directions

It will be really good if you can create a demo. I made some fixes related to dragging in `konva@5.0.2`. Not sure if it is related.

> Another thing is that sometimes tr suddenly unattaches itself from its nodes.

Same, need a demo. Probably need to check your logic of detaching.

**Comment by enriqueerrando** [comment] 2020-04-24 20:10
I'll try konva 5.0.2 on monday and if still not working from my end I'll make those demos ;)

Thanks a lot!

**Comment by enriqueerrando** [comment] 2020-04-24 20:12
> Same, need a demo. Probably need to check your logic of detaching.

BTW, what would be the correct way of detaching a specific node? As u said, maybe that one has arised because of my logic.

**Comment by lavrton** [comment] 2020-04-24 20:51
Just use `nodes(shapes)` methods with a new array of transforming nodes.

**Comment by enriqueerrando** [comment] 2020-04-27 16:01
Hi again ;)

I've just tested konva 5.0.2 and both of my issues are fixed now, great! I think it's pretty much done!

One question: Now that transformer nodes are not part of a single group, how shoud I move them with arrow keys? Do I have to move each one of them individually or there's a better way?

Thanks a lot!

**Comment by lavrton** [comment] 2020-04-28 15:16
> Do I have to move each one of them individually

Yes.

**Comment by enriqueerrando** [comment] 2020-04-28 15:31
> > Do I have to move each one of them individually
> 
> Yes.

Wouldn't be great having support for moving nodes and transformer child nodes around with arrow keys instead of having to write custom code since it's the expected behaviour of selected nodes? 

I'm not trying to load u up with more work, hahahaha!! U've already done a great job with this multiselection feature. It's just an interesting thing to take into consideration for future improvements ;)

**Comment by enriqueerrando** [comment] 2020-04-28 19:34
While testing some things, I found that now that we can add multiple nodes to a transformer, the nodes dragBoundFunc doesn't make much sense since applys to eachone individually. It would be great if we could add the dragBoundFunc param to the Tr itself. 

Would that be difficult to implement?

**Comment by lavrton** [comment] 2020-04-28 19:38
Why it doesn't make sense?

It may be simpler to just use `dragmove` event.

**Comment by enriqueerrando** [comment] 2020-04-28 20:37
I have several nodes with dragBoundFunc setup to prevent them from leaving the canvas. When I multiselect them with a tr and drag it around, each node ends dragging itself when hits the canvas limits, but the rest keep dragging and getting far away from those ended ones. 

The expected behaviour would be that when a first node hits the canvas limits, all tr nodes would end dragging all at once, preventing them from changing its relative position to the multiselection.

**Comment by enriqueerrando** [comment] 2020-04-30 10:32
BTW, does Konva fully supports ReactJS? 

Since the project is getting so big, I'm thinking on converting my code to ReactJS to make it more scalable and maintainable.

Thanks!

**Comment by lavrton** [comment] 2020-05-06 16:41
I found the solution for all cases. Already in master.

I will release later with a small breaking change for `boundBoxFunc`.

**Closed by lavrton** 2020-05-06 16:41 UTC
Labels: enhancement
