### ISSUE TITLE
touchmove stops firing when draggable is true

### ISSUE THREAD

**Issue by CosmaTrix** [konvajs/konva#403] opened 2018-06-16 11:12 UTC
Hi all,

I'm having an issue when attaching a `touchmove` event listener to a draggable shape. When the shape is set to `draggable`, the event fires few times (approx 3-5 times) and then it stops.
The example in the CodeSandbox logs `move` when moving the green square in the middle of the stage. 

[https://codesandbox.io/s/myzpr6mr89](https://codesandbox.io/s/myzpr6mr89)

Any idea why this is happening and how to solve it?

**Comment by lavrton** [comment] 2018-06-18 05:32
I think that is by design. When a shape is dragging it doesn't fire other events.
What is your use case? Why is it important to you?

**Comment by CosmaTrix** [comment] 2018-06-18 08:19
I'm working a case in which I need to use multi-touch events to pinch/rotate a shape. The implementation is actually pretty easy.
As a workaround, I'm setting draggable to false when a multi-touch event is detected and setting it back to its original value when the event is over. But I do believe that touchmove should keep firing, as that is what is actually happening when someone touches and moves their finger on their device.

I'll update the Sandbox later today, with the little class I've written so far (only zoom on pinch at the moment).

**Comment by CosmaTrix** [comment] 2018-06-18 09:04
Here's a new Sandbox with the simple class I'm writing. It can be found in the `src/Konva` folder. It extends `Konva.Rect` and implements touch gestures to allow pinch zoom in/out.
As explained in my previous comment, I'm setting the draggable value to false for multi-touch gestures and then putting it back to its original value. Checkout the onTouchMove method.

```
onTouchMove = e => {
  if (e.evt.touches.length === 2) {
    const originalDraggable = this.draggable();

    if (originalDraggable) {
      this.draggable(false);
    }

    //  zoom code

    if (this.draggable() !== originalDraggable) {
      this.draggable(originalDraggable);
    }
    }
  };
};
```

[https://codesandbox.io/s/62y8qnjy3w](https://codesandbox.io/s/62y8qnjy3w)

**Comment by gaurav-nelson** [comment] 2019-07-03 01:46
Thanks @CosmaTrix 

It works fine on Firefox but not in Chrome. Is there a fix?

**Comment by lavrton** [comment] 2019-08-08 09:26
That should be fixed with the last version v4.
You can enable hit graph on drag with `Konva.hitOnDragEnabled = true`. That will enable all events during drag&drop.

**Closed by lavrton** 2019-08-08 09:26 UTC
Labels: bug
