### ISSUE TITLE
Drag and Resize is not always working

### ISSUE THREAD

**Issue by MContagious** [konvajs/konva#1619] opened 2023-08-05 02:17 UTC
Hi,

Dragging elements and transformations (resizing) are not reliably working. I have screen recorded from konvajs website examples only

https://konvajs.org/docs/react/Transformer.html

https://www.loom.com/share/19cad981f9254455bbdb0f705e81b3ec?sid=0501a990-0893-43c9-8641-aec0a39ad65c

I was trying to drag but they are not moving. When I refresh sometimes red box only moving but not the blue box. The behaviour is not at all reliable.

**Comment by lavrton** [comment] 2023-08-06 23:54
What browser do you use?

**Comment by kishoreknowapp** [comment] 2023-08-11 18:28
I am using Brave browser. 
I don't understand why it is browser specific.

**Comment by MContagious** [comment] 2023-08-11 18:43
> What browser do you use?

Yes, I am using brave browser. I didn't try in other browsers and now I have and the examples works in chrome and edge browsers.

**Comment by lavrton** [comment] 2023-08-14 02:08
Closing as duplicate of this: https://github.com/konvajs/konva/issues/1484

**Closed by lavrton** 2023-08-14 02:08 UTC
