### ISSUE TITLE
using OffscreenCanvas for performance optimisation

### ISSUE THREAD

**Issue by kirill3333** [konvajs/konva#446] opened 2018-09-04 19:21 UTC
Hi

I think it would be great to implement https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas support in future version.

I know you have some tricks for optimization however it is more native method.

Some explanation from google https://developers.google.com/web/updates/2018/08/offscreen-canvas

**Comment by lavrton** [comment] 2018-09-04 19:58
That is definitely what I want to use sooner or later. But right now browsers support is very poor.

Probably we should adopt our API for using `OffscreenCanvas` with some fallbacks.

**Comment by ichenzhifan** [comment] 2018-09-05 07:11
Look forward to integrate the new API.

**Comment by liyuanqiu** [comment] 2018-10-17 07:29
+1
You may support OffscreenCanvas internally in this project, but you can also go another way like THREE.js.
THREE.js has no special code about OffscreenCanvas, it just gives the power to developers.
https://threejs.org/examples/?q=offs#webgl_worker_offscreencanvas

Developers import konvajs in web worker, do anything in worker. Developers give a canvas to konvajs, konvajs draw anything on it. Konvajs don't need to know whether the canvas is origin canvas or transferred canvas.

**Comment by xuzhaobin** [comment] 2019-09-17 04:42
one year later...

**Comment by aolsx** [comment] 2019-10-23 02:01
yes，We need OffscreenCanvas.

**Comment by Seblor** [comment] 2019-10-25 09:12
It looks like there has been attempts at using `offscreenCanvas` :

- https://github.com/konvajs/konva/blob/master/test/sandbox2.html
- https://github.com/konvajs/konva/blob/master/test/worker.js

No idea if those are used or even work, though.

**Comment by lavrton** [comment] 2019-10-25 15:40
Yeah, I was playing with it and probably we will have something working here. But right now I am not sure what are the real use cases of `Konva` inside a web worker with `OffscreenCanvas`.

**Comment by Seblor** [comment] 2019-10-25 15:56
Thank you for taking the time to answer :)

I actually have been trying for the last few days to improve the performance of a software I'm working on at work (running with Electron). The images I use are heavy on the rendering side (they are DOM images with a base64 SVG as src), and in some cases the user has to add a few hundreds at the same time. The rendering sometimes takes a few seconds on a mid-range desktop (I am using the batchdraw method and the other performance tips, the images can simply just be really large). This delay can be accepted by the user, but the issue is that the whole app is unresponsive while rendering. Having the rendering process taking place in a worker will allow the user to keep using the other parts of the software.

My use case may be a bit isolated, but it still is an actual "real-world" use case.

**Comment by lavrton** [comment] 2019-10-25 16:03
Yeah. The main point of `Konva` is too make canvas interactive. To listen to events, to enable drag&drop, etc. So it is not just "rendering".

I am not sure how to use the power of interactivity with the events inside a web worker.

Are your images interactive? Or you are just drawing them as visualization without any interactivity from the user?

**Comment by Seblor** [comment] 2019-10-25 16:09
The user has to be able to move rescale, and rotate the images. The interactions are real-time, thanks to the tip on using a special layer for drag & drop or other manipulations.

**Comment by caseyyee** [comment] 2020-02-21 18:23
Wanted to chime in here with a use case.  Our app uses Konva to draw textures for use in webGL, and we pipe in interactions using the _mousemove (and others) test interface.  Not ideal, but it works.  It would be huge if we can do this with Offscreen canvas, since in this case, we really don't need it to be visible/interactive.

**Comment by lavrton** [comment] 2020-02-21 23:33
@caseyyee interesting use case. Why do you need such textures? Why do use Konva to draw them? Isn't simpler to use native 2d context API?

**Comment by caseyyee** [comment] 2020-02-24 23:26
@lavrton You're probably thinking material textures, but we're actually using Konva to draw UI (It's a VR, WebXR app).  So mainly stuff like menu's, text layout and images, and dealing with interactions, which Konva is really great at.

To be a bit more specific about the implementation, we're using Konva in react via Konva-react and react-three-fiber.  So far the approach has worked well.  I'll eventually write more about what we've done here, but in the meantime happy to answer any questions about how we use Konva :)

**Comment by lavrton** [comment] 2020-02-27 14:13
@caseyyee That is interesting. I would like to know more details! Do you mix `react-konva` and `react-three-fiber`? I mean you have Konva interface inside 3d world? How to you manage events?

**Comment by caseyyee** [comment] 2020-02-27 22:00
@lavrton Yes, that's right.  react-konva and react-three-fiber.   So Konva interface is being rendered with WebGL/three in 3D/VR.

Users interact with the interface using a VR controller with a laser pointer cursor.  The cursor coordinates (raycast uv intersections) and button presses are then piped into Konva using the test interface _mousemove, _mouseenter, _mouseout, _mousedown, etc.  All the interactions are then handled as you would normally with konva-react using the various event handlers.

**Comment by jonnyleeharris** [comment] 2020-03-13 16:55
This would be useful for me.

My use case is I have 100s of pages that I need to print. Each page has 2-3 canvases on it. Needless to say if I just ask a browser to render this and press print - I will be waiting a while.

If I could render things in an OffscreenCanvas off the main thread - I'm thinking I could then export the canvases into images - giving me more options to print (e.g. generating PDFs)

**Comment by lavrton** [comment] 2020-03-15 03:29
I have very large progress here. Take a look into this demo: https://konvajs.org/docs/sandbox/Web_Worker.html



I just released `konva@4.2.0` with some small fixes to make it work inside a Web Worker.

**Please remember that at the current moment web worker support is very experimental!**
And I am not sure we will have "official" support for web workers and cover all use cases.

I am going to close the issue for now. I don't think I need to do anything more from the `Konva` side. 

But the discussion is still open! If you have any feedback - please comment here!
Is the demo helpful? Do we need anything to add to the demo or remove from it?

**Closed by lavrton** 2020-03-15 03:29 UTC
Labels: enhancement

**Comment by jonnyleeharris** [comment] 2020-03-25 14:56
@lavrton This is great news. Thanks.

I'm trying to get this working in Angular. Creating a stage without a container doesn't seem possible. Trying to figure my way around it. Any ideas?

**Comment by lavrton** [comment] 2020-03-25 17:49
I am not sure how you are try this. The offscreen demo above works inside a web worker.  There is no frameworks and DOM in this eviroment.

**Comment by jonnyleeharris** [comment] 2020-03-25 18:08
@lavrton Yes I know. Having a bit of trouble with Angular and web workers at the moment but once I'm through that I'll update here - but I think I should be able to get it working...!

Thanks!
