### ISSUE TITLE
result of path.getLength() incorrect

### ISSUE THREAD

**Issue by liucsny** [konvajs/konva#939] opened 2020-06-27 09:24 UTC
I drew a path and called path.getLength(), but found the result is not so precise.
so i drew another path in SVG and called path.getTotalLength(), the two results are different.

here is the screenshot:  
![image](https://user-images.githubusercontent.com/11475340/85918958-c900c780-b899-11ea-8da0-45a379eaf35b.png)

here is my code:

```javascript
let width = 1000,
    height = 400;

let d = 'M1.07027 18.021 C7.11502 3.14162 55.938 -9.87785 480 60'

let stage = new Konva.Stage({
  container: 'container',   // id of container <div>
  width,
  height,
})

let layer = new Konva.Layer();

let curve = new Konva.Path({
  x: 240,
  y: 40,
  data: d,
  stroke: 'black',
  strokeWidth: 4,
});
stage.add(layer);
layer.add(curve);
layer.draw();


//SVG
let svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
svg.setAttribute("width",width);
svg.setAttribute("height",height);
svg.style.backgroundColor='black';
document.getElementsByTagName('body')[0].appendChild(svg);
SVGPath = document.createElementNS('http://www.w3.org/2000/svg', 'path');
SVGPath.setAttribute("d", d);
SVGPath.setAttribute("stroke", 'white');
SVGPath.setAttribute("stroke-width", 4);
SVGPath.setAttribute("transform","translate(240,40)")
svg.appendChild(SVGPath);



console.log(curve.getLength());
console.log(SVGPath.getTotalLength());
```

**Comment by radiocity** [comment] 2021-01-22 04:11
```js
// ...

const path = new Path({
  x: 0,
  y: 0,
  stroke: "#4E5FEA",
  strokeWidth: 4,
  data:
    "M307.033,470 C313.432,432.854 317.323,410.266 324,371.5 L579.5,367 C579.5,367 584.5,366 586.5,364 C588.5,362 588.5,357 588.5,357 L583.5,239 L325,240.5 C316.866,239.219 314.418,236.734 314,229 L324,173 C323.818,166.668 321.516,164.322 314,undefined H247"
});

console.log(path.getLength()); // Nan (should be ~904)
```

**Comment by lavrton** [comment] 2021-01-22 13:24
@radiocity why do you have `undefined` in your string? I don't think that is a valid case.

**Comment by radiocity** [comment] 2021-01-24 12:49
> @radiocity why do you have `undefined` in your string? I don't think that is a valid case.

Looks like the problem is a path syntax error

**Comment by lavrton** [comment] 2021-05-06 20:10
I am closing the issue for now. Konva is calculating the length roughly. If you need the exact numbers you may need to find another way to calculate the length. 

But it will be good if someone can make a pull request with a better calculations.

**Closed by lavrton** 2021-05-06 20:10 UTC
Labels: bug
