### ISSUE TITLE
Maintaining objects on different image resolution

### ISSUE THREAD

**Issue by santosmken** [konvajs/konva#338] opened 2018-02-09 17:22 UTC
Hello, I am new to this library and I read some good feedbacks about it. I have a question regarding on maintaining the objects from a smaller image to a bigger image. For example I have multiple pins on a floor plan then I want to replace it with a same floor plan but a higher resolution. Now what I want to achieve is I want the old pins to be place on the proper position even if the image resolution is different. Currently I'm using fabric js but I can't find some workaround or example for it and I'm planning to change it to konva.

**Comment by lavrton** [comment] 2018-02-10 06:19
So do you want just replace images?
I can keep the same size of a floor image or recalculate the position of pings.

**Comment by santosmken** [comment] 2018-02-10 16:44
Yes but only the image wherein the pins are placed. For example a picture of a farm wherein there is a carabao on a tree. If I replace the picture of farm which is now much bigger like 400x400 to 800x800 size and the carabao should still be placed on the same position like from the old picture of a farm.

**Comment by lavrton** [comment] 2018-02-13 01:54
I guess you just need to double your coordinates. Or apply scale (<1) to a large image.

**Comment by lavrton** [comment] 2018-02-13 01:55
I will close the issue. Because it is not a bug/features. You can StackOverflow for such questions.

**Closed by lavrton** 2018-02-13 01:54 UTC

**Comment by santosmken** [comment] 2018-02-13 02:17
Okay thanks for your response. Last question, what about maintaining the object size even on zoom? So it's like I set the image as 20px even if I zoom in/out into it, it should still be 20px no matter what zoom level it is.
