### ISSUE TITLE
Align center on textPath not correctly centered

### ISSUE THREAD

**Issue by SnooHD** [konvajs/konva#902] opened 2020-05-03 14:14 UTC
See the fiddle here:
https://jsbin.com/hapipuluhi/1/edit?html,js,output

Seems like the text alignment is a bit off :(

Another thing i noticed, is that the alignment is dealing pretty weird with spaces.
https://jsbin.com/cenutasoci/1/edit?html,js,output

And afraid its also te case with letter-spacing..
https://jsbin.com/cuxojaxusu/1/edit?html,js,output

**Comment by lavrton** [comment] 2020-05-04 20:21
As I can see the demo is using `v4`. Try `v5` it works better. There were some fixes during v4.

Still not perfect for all cases, but better.

**Comment by SnooHD** [comment] 2020-05-05 09:18
Yes i see.
I know this is complicated stuff due to fonts just being a b*tch when it comes to kerning.
My intention is to have a slider where you can set a percentage of how much text will be curved.
I do wonder if you could help me thing of something where i could get this to work.. 

I have managed to get it work using SVG textPath, but i prefer using Konva as it deals with many more things i else have to reinvent the wheel for.

I will try to create a codepen with it so you have a better understanding of what i need.

**Comment by SnooHD** [comment] 2020-05-05 10:31
Ended up using codesandbox:
https://to3lm.sse.codesandbox.io/

My intention is to use this in combination with customizable fonts & text attributes like font-weight, letter-spacing etc.

**Comment by gxlinhai** [comment] 2020-08-08 07:18
I'm looking forward to it !

**Comment by goldenjayr** [comment] 2020-12-15 18:13
> Yes i see.
> I know this is complicated stuff due to fonts just being a b*tch when it comes to kerning.
> My intention is to have a slider where you can set a percentage of how much text will be curved.
> I do wonder if you could help me think of something for how i could get this to work..
> 
> I have managed to get it work using SVG textPath, but i prefer using Konva as it deals with many more things i else have to reinvent the wheel for.
> 
> I will try to create a codepen with it so you have a better understanding of what i need.
> 
> EDIT:
> Ended up using codesandbox:
> https://to3lm.sse.codesandbox.io/
> 
> My intention is to use this in combination with customizable fonts & text attributes like font-weight, letter-spacing etc.

Can you give me the source code of this example. Thanks

**Comment by lavrton** [comment] 2021-05-06 20:08
I am closing the issue as a very low priority. The issue is a hard one. But I will be happy if someone can help me with a good pull request.

**Closed by lavrton** 2021-05-06 20:08 UTC
Labels: bug
