### ISSUE TITLE
Error in Konva.d.ts

### ISSUE THREAD

**Issue by RakeshChouhan** [konvajs/konva#496] opened 2018-11-14 23:33 UTC
Hi ,
I am using Konva with Typescript 3.x, I am getting an parsing error while adding any element to the Konva.Layer.

layer.add(new Konva.Line({
                points: [Math.round(i * padding) + 0.5, 0, Math.round(i * padding) + 0.5, height],
                stroke: '#ccc',
                strokeWidth: 1,
            }));

error is showing in the add method 
[ts] Property 'add' does not exist on type 'Layer'

Also I can see an parsing error in Konva.d.ts file where Layer extends the Container.

[ts] Generic type 'Container<T, Node>' requires 2 type argument(s).

Can anyone help me on this ??

**Comment by lavrton** [comment] 2018-11-15 20:43
I don't have any parsing errors with `konva.d.ts`. Just tried this `tsc ./konva.d.ts`.

What konva and typescript versions you are using?

**Comment by RakeshChouhan** [comment] 2018-11-18 05:04
I am using Konva5 with Typescript 2.6

**Comment by lavrton** [comment] 2018-11-26 16:45
I am closing the issue for now, because I don't see what is not working. I do not see typescript errors. If the issue is still here, please provide more information.

**Closed by lavrton** 2018-11-26 16:45 UTC
