### ISSUE TITLE
touch events and drag events give different event.target results

### ISSUE THREAD

**Issue by VividWombat** [konvajs/konva#601] opened 2019-03-10 23:22 UTC
I'm refactoring an existing react app (not my code) to support touch events (IOS/Android browser). I've added touch events using the onTap/Touch methods, which do work, but work differently to onDrag.

```
              <Stage
                onTouchStart={this.onTouchStart}
                onTouchMove={this.onTouchMove}
                onTouchEnd={this.onTouchEnd}
                onTap={this.onTap}
                ...
```
I'm creating shapes using  a Group with Rect/Text/Circle children. only Group is draggable. In Chrome on a PC this correctly fires a dragstart event, with event.target returning the Group.

When I test on a tablet, event.target returns info for the Rect/Text/Circle, which arent draggable, instead of the Group. Sometimes I also get info for the Stage. Is this expected ? Using Chrome I can emulate this on a PC, so have access to console to see what happens.

From the docs, its seems that touchstart and dragstart should return the same info. I will try to recreate this in a jsfiddle

**Comment by lavrton** [comment] 2019-03-11 01:24
I can't reproduce. I was trying this: https://jsbin.com/xakuhebaqi/1/edit?html,js,output

It always logs layer for me.

**Comment by VividWombat** [comment] 2019-03-11 09:34
not easy to create a simple demo, as I suspect there's some interaction that causes this. react-konva is wrapped with react-dnd (to drop stuff onto the stage)

**Comment by VividWombat** [comment] 2019-03-11 16:09
I removed react-dnd, to see what difference it makes. touch event now generate dragstart event as well as touch events

`{type: "dragstart", target: Group, evt: TouchEvent, currentTarget: Layer}
currentTarget: Layer {_id: 792, eventListeners: {…}, attrs: {…}, index: 1, parent: Stage, …}
evt: TouchEvent
targetTouches: TouchList {0: Touch, length: 1}
touches: TouchList {0: Touch, length: 1}
type: "**touchmove**"
view: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
target: Group {_id: 791, eventListeners: {…}, attrs: {…}, index: 14, parent: Layer, …}
type: "**dragstart**"`

will continue trying to isolate this

**Comment by VividWombat** [comment] 2019-03-14 22:57
still trying to isolate this issue. have created some code to test it. 

https://codesandbox.io/s/w66k8v7jk

this behaves differently on tablet/ipad - rect/text will either not appear or movement is erratic. text position changes within the group, but isnt changed in code

shadow is used differently to most of the demo code, where its changed dynamically to show the drop target (onto a grid)

**Comment by lavrton** [comment] 2019-03-18 17:56
@VividWombat 
You have this code in the demo: `onTouchEnd={this.handleDragEnd}`. `touchend` event may fire outside of shapes, like on empty areas of the stage.
So this code:
```
handleDragEnd = e => {
    var shape = e.target;
```
Will be not correct. Because `e.target` will be a stage, not a shape.

**Comment by VividWombat** [comment] 2019-03-18 18:45
I did a change, just to see what happens with the stage. Have changed back to the original code, which has the events triggered on the shape/group

**Comment by VividWombat** [comment] 2019-03-18 19:34
http://prntscr.com/mznbya

this shows the issue with text and rect being different place. both are inside a group, so should never be separated like this. works correctly on dragmove but not on touchmove. not sure how to debug this further.

I added a check to make sure there's no stage events corrupting things

**Comment by lavrton** [comment] 2019-03-18 20:35
@VividWombat  do not use `attrs` from the node. It is not public and not documented property
```
const {
      attrs: { x: posX, y: posY }
    } = e.target;
```

`e.target.attrs.x` may be undefined. It produces wrong calculations. Instead, you need this: `e.target.x()`

**Comment by VividWombat** [comment] 2019-03-18 21:21
thanks. didnt know you shouldnt access node atrr directly. I updated code and its better, but still a difference with text position. Added a check for Text, in case that triggered an event.

I only set shadow on the Rect, using shape.shadowOffset(). But it seems that Text is also getting offset on the first drag. after the first drag, its OK. and only for touchmove

```
shadowOffsetX: 25
shadowOffsetY: 25
text: "some text"
width: 100
x: 25
y: 25
```

which is consistent with what happens - http://prntscr.com/mzoshr

**Comment by lavrton** [comment] 2019-03-18 23:36
Why don't you use just drag events? Why do you need touch events here?

If you want to get a rectangle inside the handler you can do this:
```
e.currentTarget.findOne('Rect');
```

Or you can use React's refs to save the group in component instance.

**Comment by VividWombat** [comment] 2019-04-09 22:24
I'm using drag events as they fire as well as touch events. but the offsetX/offsetY  arent in the event.evt. so I'm doing this 

    if(event.evt.type === 'touchmove'){
      console.log(event.target);
      offsetX = event.target.getAttr('x');
      offsetY = event.target.getAttr('y');
    }
    else if(event.evt.type === 'mousemove'){
      offsetX = event.evt.offsetX;
      offsetY = event.evt.offsetY;

**Comment by lavrton** [comment] 2019-07-31 12:15
I am closing the issue for now. Add a comment if you have more info about the reproducing.

**Closed by lavrton** 2019-07-31 12:15 UTC
