### ISSUE TITLE
Light line issue

### ISSUE THREAD

**Issue by NPetrovs** [konvajs/konva#431] opened 2018-08-07 16:44 UTC
I am creating a project using your awesome KonvaJS framework.
However I am having an issue:
I am drawing a soundwave with a lot of rectangles put together using this code:

```
            var rectangle = new Konva.Rect({
                x: x,
                y: y,
                width: 1,
                height: h,
                perfectDrawEnabled: false
            });
```

<img width="703" alt="screen shot 2018-08-06 at 00 01 50" src="https://user-images.githubusercontent.com/13074219/43790088-4a89f3ca-9a7a-11e8-8b06-5e684ca0c757.png">

As you can see in the first image, it has light grey lines over it and I am not sure why.
But it has to be solid black like in this example:

<img width="821" alt="screen shot 2018-08-06 at 00 02 33" src="https://user-images.githubusercontent.com/13074219/43790100-535ebf3a-9a7a-11e8-8dd7-591c7f14aef9.png">

Any ideas about this?

**Comment by MaxGraey** [comment] 2018-08-07 19:58
You can try several approaches:
- slightly increase width to `1.01` for example.
- make sure `x` value is quantize to `1 / devicePixelRatio`. For example if `devicePixelRatio` is equal `1` your `x` value sholdn't contain fractional part, but if `2.0`, `x` value should round to `0.5` and possible values for example `0.5, 1,  1.5, 2, 2.5, ...`.

**Comment by NPetrovs** [comment] 2018-08-07 21:38
Thank you for looking into this, however my x coordinate is always a round incremented number - 1, 2, 3, 4, 5.

**Comment by MaxGraey** [comment] 2018-08-07 21:40
Could you show full example?

**Comment by NPetrovs** [comment] 2018-08-07 21:45
This is the loop, which calls draw bar function:

`for (var k = 0; k < this._waveformWidth; k += 1) {
        var ch = parseFloat(channel[k]);
        this._drawBar(k, ch);
  }`

and this is drawBar function:

`
 var w = this._barWidth;
 var y = this._canvasHeight / 2 - h;

var rectangle = new Konva.Rect({
                x: i,
                y: y,
                width: w,
                height: h,
                perfectDrawEnabled: false
            });

            rectangle.setAttrs(this._applyFillOrBlur(h));
            this._waveGroup.add(rectangle);
        }`

**Comment by MaxGraey** [comment] 2018-08-07 21:49
What is value of `this._barWidth`? Is it `1`? And could you show what happening with rectangles after loop. You add it to layer or group? Need more info

**Comment by NPetrovs** [comment] 2018-08-07 21:52
Yes, barWidth is 1;
Each rectangle is added to the `this._waveGroup = new Konva.Group();`

then this group is added to the `this._waveLayer = new Konva.Layer({hitGraphEnabled: false});`

and finaly waveLayer is added to the stage and drawn.

**Comment by NPetrovs** [comment] 2018-08-07 21:53
If that helps, I am using iMac with retina display. devicePixelRatio is 2

**Comment by MaxGraey** [comment] 2018-08-07 21:55
Ok, what happening in `_applyFillOrBlur`? I can't see any problems in existing code. It will better if you share full example on jsfiddle or codepen.

**Comment by NPetrovs** [comment] 2018-08-07 21:58
this is a full class - https://pastebin.com/m3hJa29h

**Comment by MaxGraey** [comment] 2018-08-07 22:01
Ok, it seems I see where problem. Try to disable blur (this._waveBlur = false). And see what happened. Is horizontal gaps still present?

**Comment by MaxGraey** [comment] 2018-08-07 22:06
Also this (line 353):
```js
this._barWidth = parseFloat(event.target.value);
```
better change to:
```js
this._barWidth = Math.max(1, parseFloat(event.target.value));
```

**Comment by NPetrovs** [comment] 2018-08-07 22:13
<img width="827" alt="screen shot 2018-08-08 at 01 12 35" src="https://user-images.githubusercontent.com/13074219/43805382-315ef692-9aa8-11e8-9654-069ed1831a19.png">

Problem is still there. :(

Problem is still there. :(

**Comment by MaxGraey** [comment] 2018-08-07 22:15
Ok, just scale your width by `1.01` factor like `this._barWidth * 1.01`

**Comment by MaxGraey** [comment] 2018-08-07 22:19
Oh, no I found where you use fractionals=)
```js
this._drawBar(k + (this._canvasWidth / 10), ch);
```
replace to:
```js
this._drawBar(k + Math.ceil(this._canvasWidth / 10), ch);
```

**Comment by NPetrovs** [comment] 2018-08-07 22:29
I fixed these fractionals, but the result is the same. If I increase bar width by 0.2, it becomes better, but it is also becoming too fat and ugly. :(

**Comment by NPetrovs** [comment] 2018-08-07 22:31
<img width="815" alt="screen shot 2018-08-08 at 01 30 31" src="https://user-images.githubusercontent.com/13074219/43805993-b17305ba-9aaa-11e8-9daf-d5ca24601585.png">

increased by 0.2

**Comment by MaxGraey** [comment] 2018-08-07 22:34
Fixed in all places? I found two. Could you share fixed version?

**Comment by MaxGraey** [comment] 2018-08-14 18:32
I'm blind without full working example. But try this, when drawing bar: 

```js
var rectangle = new Konva.Rect({
  x: Math.floor(x), // <--- instead raw x
  y: y,
  width: Math.ceil(width), // <--- instead raw width
  height: height,
  perfectDrawEnabled: false
});
```

**Comment by NPetrovs** [comment] 2018-08-14 18:37
@MaxGraey Same result. :(
It obviously has to do something with screen pixel ratio, because if I run same script on node.js backend, it generates absolutely fine.

**Comment by NPetrovs** [comment] 2018-08-14 19:11
@MaxGraey This is closeup of 5 rectangles I drew:

<img width="412" alt="screen shot 2018-08-14 at 22 10 46" src="https://user-images.githubusercontent.com/13074219/44112848-ee73f636-a00e-11e8-9e6d-e3d712c16e4c.png">

**Comment by MaxGraey** [comment] 2018-08-14 19:15
Ok, I see you have fractional coordinates, so investigate your code.

**Comment by NPetrovs** [comment] 2018-08-14 19:16
@MaxGraey Could it possible be something like this? 
https://stackoverflow.com/questions/9311428/draw-single-pixel-line-in-html5-canvas

**Comment by MaxGraey** [comment] 2018-08-14 19:31
Nope. This true for hairline bit not for rectangles. See this:
http://jsfiddle.net/4ghp7dyo/

**Comment by NPetrovs** [comment] 2018-08-14 20:41
` MW.Generator.PosterCanvas.prototype.fitStageIntoParentContainer = function () {
        var container = document.querySelector('#canvas-holder');
        var containerWidth = container.offsetWidth;

        var factor = 0.8;

        if (this._variant.orientation === 'vertical') {
            factor = 0.5;
        }

        var scale = containerWidth / this._variant.preset.canvasWidth * factor;
        this._stage.width(this._variant.preset.canvasWidth * scale);
        this._stage.height(this._variant.preset.canvasHeight * scale);
        this._stage.scale({ x: scale, y: scale });
        this._stage.draw();
    };`

I think this function might be doing this. since it is scaling everything together including rectangles. What do you think?

**Comment by lavrton** [comment] 2018-08-21 09:16
I will close the issue. I think it is more related to canvas directly, then to Konva. Also I think it will make sense to draw into canvas directly or use custom shape, instead of creating tons of `Konva.Rect`s.

If you think that the issue is related to the Konva, then please provide a very small demo.
Also you may try to set `Konva.pixelRatio = 1` to fix the issue.

**Closed by lavrton** 2018-08-21 09:16 UTC
